platform :ios, '13.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_install_ios_pods(ios_application_path = nil)
  require File.expand_path(File.join('flutter', 'podhelper'), File.dirname(__FILE__))
  flutter_install_all_ios_pods(ios_application_path)
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!
  flutter_install_ios_pods(File.dirname(File.realpath(__FILE__)))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
